export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_COMMONICLIST = 'GET_ICLIST';
export const IC_LOADING = 'IC_LOADING';
export const GET_NEWSDETAILS = 'GET_NEWSDETAILS';
export const GET_DEALSDETAILS = 'GET_DEALSDETAILS';
export const GET_REPORTSDETAILS = 'GET_REPORTSDETAILS';


