// const end_point = `https://coe-test-events-website.pantheonsite.io`;
//const end_point = `https://webex-events-website.pantheonsite.io`;
const end_point = `https://events.globaldata.com`;
const api_url = {
  live_url: `${end_point}`,
  authCookie: `${end_point}/api/user/generate_auth_cookie`,
  getBanners: `${end_point}/api/user/get_banners`,
  eventList: `${end_point}/api/user/get_all_events`,
  eventInfo: `${end_point}/api/user/get_event_info`,
  bookmark: `${end_point}/api/user/add_bookmarks`,
  userDetails: `${end_point}/api/user/get_profile_detail_list`,
  updateProfile: `${end_point}/api/user/update_profile/`,
  getProfile: `${end_point}/api/user/get_profile`,
  attendeesList: `${end_point}/api/user/get_attendees/`,
  attendeesSearch: `${end_point}/api/user/search_attendees`,
  currentUserInfo: `${end_point}/api/user/get_currentuserinfo`,
  agendaList: `${end_point}/api/user/get_agenda/`,
  agendaListNew: `${end_point}/api/user/get_agenda_list/`,
  agendaDetails: `${end_point}/api/user/agenda_details`,
  agendaRecVideo_reset: `${end_point}/api/user/simulive_reset_session`,
  resetSession_Res: `${end_point}/api/user/simulive_fetch_video_session_data`,
  checkSessionStatus: `${end_point}/api/user/simulive_fetch_video_session_data`,
  simuliveJoinSession: `${end_point}/api/user/simulive_join_session`,
  resetSession: `${end_point}/api/user/simulive_reset_session`,
  myFavourites: `${end_point}/api/user/get_myfavorites`,
  companies: `${end_point}/api/user/get_companies`,
  companyProfile: `${end_point}/api/user/get_company_profile`,
  companiesSearch: `${end_point}/api/user/search_companies`,
  exhibitors: `${end_point}/api/user/get_exhibitor`,
  exhibitorsSearch: `${end_point}/api/user/search_exhibitors`,
  exhibitorsDetail: `${end_point}/api/user/get_exhibitor_individual`,
  potentialRelation: `${end_point}/api/user/get_potentailrelationships`,
  productList: `${end_point}/api/user/get_products_info/`,
  productSearch: `${end_point}/api/user/search_products`,
  productDetail: `${end_point}/api/user/get_products_deatil_page`,
  sponsorDetail: `${end_point}/api/user/sponsor_details_list`,

  meetingList: `${end_point}/api/user/get_my_schedule/`,

  FeedList: `${end_point}/api/user/get_str`,
  getToUsers: `${end_point}/api/user/get_to_users`,
  createMessage: `${end_point}/api/user/create_message`,
  inboxGetMessage: `${end_point}/api/user/get_messages`,
  meetingSlotDateInfo: `${end_point}/api/user/get_meetings_slotdate_info`,
  meetingAvailability: `${end_point}/api/user/get_meetings_availability`,
  updateMeetingSlotStatus: `${end_point}/api/user/update_meeting_slot_status`,
  meetingAttendeesInfo: `${end_point}/api/user/get_meetings_attendees_info`,
  meetingRequest: `${end_point}/api/user/create_meating`,
  myRelations: `${end_point}/api/user/get_myrelationships`,
  ignoreConnections: `${end_point}/api/user/ignore_connections`,
  JoinAgenda: `${end_point}/api/user/join_agenda_session`,
  launchMeeting: `${end_point}/api/user/launch_meeting`,
  keyStats: `${end_point}/api/user/get_keystatistics/`,
  latestMembers: `${end_point}/api/user/get_latest_members/`,
  speakersList: `${end_point}/api/user/get_speakers`,
  sponsorsList: `${end_point}/api/user/get_sponsors`,
  sponsor_types: `${end_point}/api/user/get_sponsor_types/`,
  meeting_status_update: `${end_point}/api/user/meeting_status_update`,
  neutralImage: `${end_point}/wp-content/plugins/peepso-core/assets/images/avatar/user-neutral.png`,
  getHelp: `${end_point}/api/user/get_help`,
  addContact: `${end_point}/api/user/add_contact`,
  saveChatLog: `${end_point}/api/user/save_daily_co_chat_log/`,
  chatHistory: `${end_point}/api/user/userMeetingChatHistory/`,
  getQuestionsAndAnswers: `${end_point}/api/user/getQuestionsAndAnswers/`,
  saveQuestionandAnswer: `${end_point}/api/user/saveQuestionandAnswer/`,
  daily_save_user_log: `${end_point}/api/user/daily_save_user_log`,
};

export default api_url;
