const globalstyleConfig = {
  mT10: {
    marginTop: 10,
  },
  mT20: {
    marginTop: 20,
  },
  mVT10: {
    marginVertical: 10,
  },
  textCenter: {
    flex: 1,
    textAlign: "center",
    textAlignVertical: "center",
  },

  container: {
    flex: 1,
    //padding: 16,
  },

  cardsWrapper: {
    marginTop: 20,
    width: "90%",
    alignSelf: "center",
  },

  //**radio button start **/
  radioButton: {
    container: {
      marginBottom: 15,
      textAlign: "center",
      // alignItems: 'center',
      //alignSelf:'center',
      //justifyContent: 'center',
      flexDirection: "row",
      marginLeft: 80,
      //justifyContent: 'space-between',
    },
    radioCircle: {
      height: 30,
      width: 30,
      borderRadius: 100,
      borderWidth: 2,
      borderColor: "#2F283D",
      alignItems: "center",
      alignSelf: "center",
      justifyContent: "center",
    },
    selectedRb: {
      width: 15,
      height: 15,
      borderRadius: 50,
      backgroundColor: "#00DEA5",
    },
    radioText: {
      marginRight: 0,
      paddingLeft: 20,
      paddingTop: 4,
      fontSize: 16,
      color: "#000",
      fontWeight: "600",
    },
  },
  //**radio button end **/

  //text input picker
  textInputPicker: {
    // height: 46,
    backgroundColor: "#fff",
    borderRadius: 5,
    marginTop: 20,
    //padding: 10,
    width: "90%",
    borderWidth: 1,
    borderColor: "#D3D3D3",
    alignSelf: "center",
  },

  //button
  buttonLabel: {
    color: "#2F283D",
    fontSize: 16,
    fontWeight: "bold",
    textTransform: "capitalize",
  },

  //**card view start**//
  card: {
    flex: 1,
    //height: "auto",
    width: "98%",
    alignSelf: "center",
    justifyContent: "center",
    marginVertical: 10,
    flexDirection: "row",
    shadowColor: "#999",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
    elevation: 5,
    //borderWidth: 0.2,
    borderRadius: 8,
  },
  //profile image start
  cardImgWrapper1: {
    flex: 1,
    borderRightWidth: 0,
    borderColor: "#fff",
    borderLeftWidth: 0,
    borderRadius: 8,
    backgroundColor: "#fff",
    borderBottomRightRadius: 0,
    borderTopRightRadius: 0,
  },
  cardImg1: {
    height: "100%",
    width: "100%",
    borderColor: "#fff",
    alignSelf: "center",
    borderRadius: 8,
    borderBottomRightRadius: 0,
    borderTopRightRadius: 0,
    borderLeftWidth: 0,
  },
  iconWidth: {
    alignSelf: "center",
    justifyContent: "center",
    marginTop: 14,
    width: 55,
    height: 55,
    marginLeft: 10,
    borderRadius: 30,
  },
  // profile image end
  cardInfo: {
    flex: 3,
    padding: 10,
    borderColor: "#fff",
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderRadius: 8,
    backgroundColor: "#fff",
    //borderBottomRightRadius: 0,
    //borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderTopLeftRadius: 0,
  },

  //speakers card/Recommended
  cardInfo2: {
    flex: 3,
    padding: 10,
    borderColor: "#fff",
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderRadius: 8,
    backgroundColor: "#fff",
    borderBottomRightRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderTopLeftRadius: 0,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "bold",
    lineHeight: 24,
  },
  cardDesg: {
    fontSize: 14,
    fontWeight: "600",
    color: "#444",
    lineHeight: 20,
  },
  cardDetails: {
    fontSize: 13,
    // fontWeight:'600',
    color: "#444",
  },
  //**card view end**//

  //**Agenda screen start**//
  agenda: {
    tracks: {
      paddingLeft: 12,
      alignSelf: "flex-start",
      fontSize: 18,
      lineHeight: 24,
      fontWeight: "bold",
      color: "#00dea5",
      paddingBottom: 6,
      paddingTop: 6,
    },
    tracksSub: {
      paddingLeft: 12,
      alignSelf: "flex-start",
      fontSize: 15,
      fontWeight: "bold",
      color: "#1E1727",
      paddingBottom: 6,
      paddingTop: 6,
    },
    listSection: {
      borderWidth: 0.5,
      borderColor: "#ddd",
      margin: 10,
      borderRadius: 5,
    },
    card: {
      alignSelf: "center",
      justifyContent: "center",
      marginVertical: 10,
      flexDirection: "row",
      shadowColor: "#999",
      shadowOffset: { width: 2, height: 1 },
      shadowOpacity: 0.8,
      shadowRadius: 3,
      borderRadius: 8,
      padding: 15,
    },
    cardInfo: {
      // marginRight:20,
      flex: 2,
      padding: 8,
      borderColor: "#ddd",
      borderWidth: 1,
      borderRadius: 8,
      backgroundColor: "#f2f2f2",
      //elevation: 5,
      // borderBottomRightRadius: 0,
      // borderTopRightRadius: 0,
    },
    addTrack: {
      backgroundColor: "#fff",
      borderRadius: 5,
      padding: 4,
      marginBottom: 5,
    },
    addTrackText: {
      textAlign: "center",
      fontSize: 12,
      color: "#dd0000",
      fontWeight: "bold",
    },
    dateTimeParent1: {
      flex: 1,
      justifyContent: "space-between",
      flexDirection: "row",
    },
    dateTimeParent2: {
      height: 22,
      backgroundColor: "#00dea5",
      //width: 145,
      paddingHorizontal: 10,
      color: "white",
      textAlign: "center",
      padding: 2,
      marginLeft: 2,
      marginBottom: 5,
      borderRadius: 5,
      marginTop: 2,
    },
    dateTimeText: {
      textAlign: "center",
      color: "#444",
      fontSize: 12,
      fontWeight: "bold",
    },
    agendaTitle: {
      fontSize: 12,
      color: "#444",
    },
    addToCalendarParent: {
      width: 130,
      backgroundColor: "#00dea5",
      marginLeft: 4,
      marginRight: 4,
      paddingTop: 4,
      paddingLeft: 5,
      paddingRight: 5,
      paddingBottom: 4,
      marginTop: 8,
      borderRadius: 5,
    },
    addToCalendarText: {
      fontSize: 12,
      color: "#444",
      fontWeight: "bold",
      textAlign: "center",
    },
    noSessions: {
      flex: 1,
      textAlign: "center",
    },
  },
  //**Agenda screen end**//
  //**Agenda Details screen start**//
  agendaDetails: {
    container: {
      flex: 1,
      padding: 16,
    },
    title: {
      fontWeight: "bold",
      fontSize: 16,
      color: "#00dea5",
    },
    addTrack: {
      marginTop: 10,
      //width: 80,
      backgroundColor: "#f1f1f1",
      borderRadius: 5,
      padding: 6,
      marginBottom: 5,
    },
    addTrackText: {
      textAlign: "center",
      fontSize: 12,
      color: "#fff",
      fontWeight: "bold",
      flexWrap: "wrap",
    },
    dateTime: {
      backgroundColor: "#00dea5",
      width: "62%",
      color: "white",
      textAlign: "center",
      padding: 2,
      //marginLeft: 3,
      //marginBottom: 5,
      borderRadius: 5,
      marginTop: 2,
    },
    dateTimeText: {
      fontSize: 12,
      color: "#444",
      fontWeight: "bold",
      textAlign: "center",
      paddingTop: 4,
      paddingBottom: 3,
    },
    addCalendar: {
      backgroundColor: "#00dea5",
      width: "35%",
      color: "white",
      textAlign: "center",
      padding: 2,
      marginLeft: "3%",
      marginBottom: 5,
      borderRadius: 5,
      marginTop: 2,
    },
    addCalendarText: {
      fontSize: 12,
      color: "#444",
      fontWeight: "bold",
      textAlign: "center",
      paddingTop: 4,
      paddingBottom: 3,
    },
    meetingStartEnd: {
      marginVertical: 10,
      fontWeight: "bold",
      fontSize: 16,
      color: "#444",
    },
    speakerText: {
      fontWeight: "bold",
      fontSize: 16,
      color: "#00dea5",
    },
    card1: {
      flex: 1,
      height: "auto",
      width: "98%",
      alignSelf: "center",
      justifyContent: "center",
      marginVertical: 10,
      flexDirection: "row",
      shadowColor: "#999",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.8,
      shadowRadius: 3,
      elevation: 5,
      //borderWidth: 0.2,
      borderRadius: 8,
    },
    cardImgWrapper: {
      //height: 210,
      //width: "100%",
      flex: 1,
      borderRightWidth: 0,
      borderColor: "#fff",
      borderLeftWidth: 0,
      borderRadius: 8,
      backgroundColor: "#fff",
      borderBottomRightRadius: 0,
      borderTopRightRadius: 0,
    },
    cardImg1: {
      height: "100%",
      width: "100%",
      borderColor: "#fff",
      alignSelf: "center",
      borderRadius: 8,
      //borderBottomRightRadius: 0,
      //borderTopRightRadius: 0,
      //borderLeftWidth: 0,
      marginBottom: 15,
    },
    iconWidth: {
      alignSelf: "center",
      justifyContent: "center",
      marginTop: 14,
      width: 60,
      height: 60,
      marginLeft: 10,
      borderRadius: 30,
    },
    cardInfo: {
      flex: 3,
      padding: 10,
      borderColor: "#fff",
      borderLeftWidth: 0,
      borderRightWidth: 0,
      borderRadius: 8,
      backgroundColor: "#fff",
      //borderBottomRightRadius: 0,
      //borderTopRightRadius: 0,
      borderBottomLeftRadius: 0,
      borderTopLeftRadius: 0,
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: "bold",
      lineHeight: 24,
    },
    cardDesg: {
      fontSize: 14,
      fontWeight: "600",
      color: "#444",
      lineHeight: 20,
    },
  },
  //**Agenda Details screen end **//

  //**favorites start**//
  favorites: {
    card: {
      width: "98%",
      alignSelf: "center",
      justifyContent: "center",
      marginVertical: 10,
      flexDirection: "row",
      shadowColor: "#999",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.8,
      shadowRadius: 3,
      elevation: 5,
      //borderWidth: 0.2,
      borderRadius: 8,
    },
    cardInfo: {
      flex: 1,
      flexDirection: "column",
      padding: 10,
      borderColor: "#fff",
      borderLeftWidth: 0,
      borderRadius: 8,
      backgroundColor: "#fff",
      //borderBottomRightRadius: 0,
      //borderTopRightRadius: 0,
    },
    agendaCardDetails: {
      color: "#444",
      flexDirection: "row",
      paddingLeft: 2,
      borderRadius: 5,
    },
    type: {
      backgroundColor: "#00DEA5",
      fontSize: 15,
      fontWeight: "bold",
      paddingTop: 3,
      paddingBottom: 3,
      borderRadius: 3,
      paddingLeft: 8,
      paddingRight: 8,
      color: "#2F283D",
    },
    //title text start
    title: {
      color: "#000",
      fontSize: 15,
      fontWeight: "bold",
      paddingTop: 5,
    },
    //title text end
    //company name and job title text start
    company: {
      color: "#000",
      fontSize: 15,
      fontWeight: "bold",
    },
    //company name and job title text end
    //**favorites end **//
  },
};

export default globalstyleConfig;
